[build]
  command = "sed -i 's/NG_APP_FIREBASE_API_KEY/'\"$NG_APP_FIREBASE_API_KEY\"'/g' src/environments/environment.prod.ts && ng build --configuration production --aot"
  publish = "dist/login-app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
